name: 'Synopsys Polaris SAST Check'
description: 'Polaris SAST runner'
inputs:
  server_url:
    description: 'URL of the polaris server instance'
    required: true
  access_token:
    description: 'Access token for accessing the polaris server instance'
    required: true
runs:
  using: "composite"
  steps:
  - run: export POLARIS_SERVER_URL=${{ inputs.server_url }}
    shell: bash
  - run: export POLARIS_ACCESS_TOKEN=${{ inputs.access_token }}
    shell: bash
  - run: wget -q ${{ inputs.server_url}}/api/tools/polaris_cli-linux64.zip
    shell: bash
  - run: unzip -j polaris_cli-linux64.zip -d /tmp
    shell: bash
  - run: /tmp/polaris analyze -w --coverity-ignore-capture-failure
    shell: bash